### ISSUE TITLE
Please add support for CentOS 7 

### ISSUE THREAD

**Issue by sentinel159868** [dodevops/puppet-graylogcollectorsidecar#1]
Hi dploeger,

great module, but...... can you please add support fpr CentOS 7????

Thx and regards

**Comment by dploeger** [comment]
Here you are. 😉  The test suite includes centos 7 tests, so it should work, but please add a comment, if it works on your site.

**Comment by sentinel159868** [comment]
YAY! Thanks a lot! I will give you a feedback after i  tested it. Thumb UP!

**Comment by sentinel159868** [comment]
Hey dploeger,

i've tested it and get the following error:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, **Can not find a valid download URL for the release**. at /etc/puppetlabs/code/environments/production/modules/githubreleases/manifests/download.pp:69:17 at /etc/puppetlabs/code/environments/production/modules/graylogcollectorsidecar/manifests/dist/redhat.pp:24 on node ....

**Comment by dploeger** [comment]
Please post your manifest or hiera snippet. The module can't find a download url for the version you requested.

**Comment by sentinel159868** [comment]
graylogcollectorsidecar::dist::redhat:
    api_url: http://log01..................int:12900/
    backends:
    - name: nxlog
      enabled: true
      binary_path: "/usr/bin/nxlog"
      configuration_path: "/etc/graylog/collector-sidecar/generated/nxlog.conf"
    collector_id: file:/etc/graylog/collector-sidecar/collector-id
    list_log_files: true
    log_max_age: '604800'
    log_path: "/var/log/graylog/collector-sidecar"
    log_rotation_time: '86400'
    node_id: api01.................int
    send_status: true
    tags:
    - nxlog
    - linux
    tls_skip_verify: true
    update_interval: '30'
    version: **0.1.1-1**

**Comment by sentinel159868** [comment]
ARGH.... my fault, sorry. the version number was the issue...... now runs puppet smooth.... but nothing changes in /etc/graylog/collector-sidecar/collector_sidecar.yml

**Comment by dploeger** [comment]
Please use a release from the collector sidecar releases page (https://github.com/Graylog2/collector-sidecar/releases). The module will ask the GitHub API for the right os package download url.  

I suppose, you meant version 0.1.1.

**Comment by sentinel159868** [comment]
Thx Dennis.....

The Puppet Agent runs without erros. But now i'm facing the problem that nothing happens :-/ ? Where's my fault? (Sorry, but i'm new in the puppet-world)

**Comment by dploeger** [comment]
Did you do the hiera_include('classes') stuff in your manifest and add the graylogcollectorsidecar class to the classes-array in your yaml-file?

**Comment by sentinel159868** [comment]
I'm configuring this via foreman. Now i've changed to the main class graylogcollectorsidecar. But also: The configuration doesn't change (i think i've to buy and puppet-cookbook :-D)
My yaml file looks for now so:

graylogcollectorsidecar:
    api_url: http://log01.................int:12900/
    backends:
    - name: nxlog
      enabled: true
      binary_path: "/usr/bin/nxlog"
      configuration_path: "/etc/graylog/collector-sidecar/generated/nxlog.conf"
    collector_id: file:/etc/graylog/collector-sidecar/collector-id
    log_max_age: '604800'
    log_path: "/var/log/graylog/collector-sidecar"
    log_rotation_time: '86400'
    node_id: build01.............int
    send_status: true
    tags:
    - nxlog
    - linux
    tls_skip_verify: true
    update_interval: '30'
    version: 0.1.1

**Comment by dploeger** [comment]
Perhaps ;-)

The test suite worked for centos 7, so I'm not quite sure, where the problem on your site is. I will look into this some more.

**Comment by sentinel159868** [comment]
Thx Dennis!

**Comment by sentinel159868** [comment]
Found it! The problem was that the collector was already installed. After i've removed it manually it worked....

**Comment by dploeger** [comment]
Ah, okay. Great. Thanks.
