### ISSUE TITLE
Should only show puppet output on change

### ISSUE THREAD

**Issue by mzhaase** [dodevops/puppet-graylogcollectorsidecar#6]
Currently, even if no configuration changed, a puppetrun with outputs 80 lines of graylog collector data. It seems every config option generates four lines of output. The output should be 0 lines if configuration did not change. This severely spams reporting and logging if used on many servers. Also, it makes it siginificantly harder to debug puppet runs.

Furthermore, refresh of collector sidecar should only be triggered on config change, not every puppet run.

**Comment by dploeger** [comment]
Are you running on 0.4.2? I know, we had this problem once, but I can't figure out, which version fixed it. We're currently running on 0.4.2 and don't have this problem.

**Comment by mzhaase** [comment]
Yes, 0.4.2. Puppet 3.5 on Debian 8.

**Comment by dploeger** [comment]
Hm, maybe it's because of Puppet 3 then. We're on Puppet 5 currently. Perhaps I can wrap up a vm to test this.

Which versions of the dependencies are you using?
We're using:
```
mod 'reidmv-yamlfile', '0.2.0'
mod 'adrien-filemapper', '1.1.3'
mod 'dodevops-githubreleases', '0.1.2'
mod 'lwf-remote_file', '1.1.3'
```
