### ISSUE TITLE
Could not autoload puppet/type/yaml_setting

### ISSUE THREAD

**Issue by mzhaase** [dodevops/puppet-graylogcollectorsidecar#9]
Puppet 5.1.0

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/yaml_setting: Could not autoload puppet/provider/yaml_setting/mapped: no such file to load -- puppetx/filemapper at`

If this is no longer under active development consider updating the README to reflect that it is currently not in a working state.

**Comment by dploeger** [comment]
It still is and it works quite well on our 5.5.1 environment.

For your error, I'm guessing, that somehow the module "adrien/filemapper" (a dependency of reidmv/yamlfile is missing as that module is providing the missing class puppetx/filemapper.

**Comment by dploeger** [comment]
In 3.1.0, the dependency on reidmv/yamlfile is removed, so this shouldn't be a problem anymore.
